### ISSUE TITLE
Ability to edit wording on website

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#106]
Would like the ability to edit the wording of each section on the home page. We will most likely be editing the about us, company location, and other wording on the home page. If we can't have an admin panel that easily allows this than I will need to know how to edit this in the code and will need a bit of guidance (I am learning a bit of html, css, and javascript so that I can more easily understand what we are capable of doing with this website).

**Comment by hermbit** [comment]
We can add fields in the admin panel for the wording, yes.

**Comment by Joshrlear** [comment]
Just saw this reply. Yes, that would be great.
