### ISSUE TITLE
contact us section

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#122]
- [x] First, the social media icons are displaying and error. shown on image below.

- [x] Second, the location bubble symbol lost its little hole in the middle as shown on image below.

- [x] Third, lets change the location to San Diego. This is where I am originally from and where most business will be conducted.

![image](https://user-images.githubusercontent.com/35083202/36160472-3b9965ee-10af-11e8-9633-12b3524bb551.png)

**Comment by hermbit** [comment]
FontAwesome, which is the provider for these icons, removed the hole in the location icon. I actually think the Globe icon might be better suited anyway:

![image](https://user-images.githubusercontent.com/28285686/36381940-3e3da1e8-1555-11e8-8a01-93d4b20f2e4a.png)

Let me know what you think

**Comment by Joshrlear** [comment]
Sure, that should be fine. please make sure that the icon and sprynamics
are on the same horizontal plane

*- Josh Lear*
*  Owner, Express RE Marketing*
*  619-507-6807*
  *Website <https://sites.google.com/view/expressremarketing/home> -
Facebook <https://www.facebook.com/expressREmarketing/>*

<https://sites.google.com/view/expressremarketing/automation>
<https://sites.google.com/view/expressremarketing/designs>
<https://sites.google.com/view/expressremarketing/home>
<https://sites.google.com/view/expressremarketing/home>

*Pricing and Project Timeline Disclaimer:*
Express RE Marketing project timeline has a *14 day deadline, *timeline
starts only after receiving the required information.* Any additional time
required will accrue a fee of $5.00/day. *
All "Template Projects" have a *Flat Fee of $15.00*. *Any changes required
on a Template Project will result in an upgrade to Custom Project pricing. *
All "Custom Projects" are subject to custom pricing. Custom Projects
include two free drafts, with a maximum of three changes per draft, drafts
unlimited.
Please submit all changes at the beginning of the day to allow a turnaround
time of 24 hours.
Print and mail set up is a *complimentary* service provided by Express RE
Marketing. We are *not responsible* for any undelivered mail or printing
and cutting issues.
Prior to receiving a final draft and/or having your final draft sent to
print and mail you must pay the invoice in full.

**Comment by Joshrlear** [comment]
Also, the map still shows boston. please change to San Diego, CA

*- Josh Lear*
*  Owner, Express RE Marketing*
*  619-507-6807*
  *Website <https://sites.google.com/view/expressremarketing/home> -
Facebook <https://www.facebook.com/expressREmarketing/>*

<https://sites.google.com/view/expressremarketing/automation>
<https://sites.google.com/view/expressremarketing/designs>
<https://sites.google.com/view/expressremarketing/home>
<https://sites.google.com/view/expressremarketing/home>

*Pricing and Project Timeline Disclaimer:*
Express RE Marketing project timeline has a *14 day deadline, *timeline
starts only after receiving the required information.* Any additional time
required will accrue a fee of $5.00/day. *
All "Template Projects" have a *Flat Fee of $15.00*. *Any changes required
on a Template Project will result in an upgrade to Custom Project pricing. *
All "Custom Projects" are subject to custom pricing. Custom Projects
include two free drafts, with a maximum of three changes per draft, drafts
unlimited.
Please submit all changes at the beginning of the day to allow a turnaround
time of 24 hours.
Print and mail set up is a *complimentary* service provided by Express RE
Marketing. We are *not responsible* for any undelivered mail or printing
and cutting issues.
Prior to receiving a final draft and/or having your final draft sent to
print and mail you must pay the invoice in full.

**Comment by hermbit** [comment]
I actually did find an option with a hole in the middle, they just moved it to a different icon name in favor of the no-hole version.

**Comment by Joshrlear** [comment]
Sounds good. All we need to do now is make sure that the icon is level
horizontally with the name sprynamics

*- Josh Lear*
*  Owner, Express RE Marketing*
*  619-507-6807*
  *Website <https://sites.google.com/view/expressremarketing/home> -
Facebook <https://www.facebook.com/expressREmarketing/>*

<https://sites.google.com/view/expressremarketing/automation>
<https://sites.google.com/view/expressremarketing/designs>
<https://sites.google.com/view/expressremarketing/home>
<https://sites.google.com/view/expressremarketing/home>

*Pricing and Project Timeline Disclaimer:*
Express RE Marketing project timeline has a *14 day deadline, *timeline
starts only after receiving the required information.* Any additional time
required will accrue a fee of $5.00/day. *
All "Template Projects" have a *Flat Fee of $15.00*. *Any changes required
on a Template Project will result in an upgrade to Custom Project pricing. *
All "Custom Projects" are subject to custom pricing. Custom Projects
include two free drafts, with a maximum of three changes per draft, drafts
unlimited.
Please submit all changes at the beginning of the day to allow a turnaround
time of 24 hours.
Print and mail set up is a *complimentary* service provided by Express RE
Marketing. We are *not responsible* for any undelivered mail or printing
and cutting issues.
Prior to receiving a final draft and/or having your final draft sent to
print and mail you must pay the invoice in full.
