### ISSUE TITLE
nav bar to top of home page

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#123]
The button home doesn't bring you to the top, it brings you just a bit below that. See image below

Second, when clicking on the sprynamics logo at the top it doesn't bring me to the top of the home page unless I am on a different page like the designer or profile. I want it to act the same as the Home button.

![image](https://user-images.githubusercontent.com/35083202/36160772-fb696478-10af-11e8-8359-03b5888461ba.png)

**Comment by hermbit** [comment]
Fixed this one!
