### ISSUE TITLE
Saved mailing lists

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#138]
change list title to "Title" and download csv to "Download List".

Also, where it says date created, it says eastern time. Is that always set to eastern or does it depend on what timezone you either uploaded it from or where you are currently?

**Comment by hermbit** [comment]
It should use the system timezone where you are currently.

**Comment by Joshrlear** [comment]
perfect! so if I access the same info on the west coast it'll use pst even
if I uploaded it in est?

*- Josh Lear*
*  Owner, Express RE Marketing*
*  619-507-6807*
  *Website <https://sites.google.com/view/expressremarketing/home> -
Facebook <https://www.facebook.com/expressREmarketing/>*

<https://sites.google.com/view/expressremarketing/automation>
<https://sites.google.com/view/expressremarketing/designs>
<https://sites.google.com/view/expressremarketing/home>
<https://sites.google.com/view/expressremarketing/home>

*Pricing and Project Timeline Disclaimer:*
Express RE Marketing project timeline has a *14 day deadline, *timeline
starts only after receiving the required information.* Any additional time
required will accrue a fee of $5.00/day. *
All "Template Projects" have a *Flat Fee of $15.00*. *Any changes required
on a Template Project will result in an upgrade to Custom Project pricing. *
All "Custom Projects" are subject to custom pricing. Custom Projects
include two free drafts, with a maximum of three changes per draft, drafts
unlimited.
Please submit all changes at the beginning of the day to allow a turnaround
time of 24 hours.
Print and mail set up is a *complimentary* service provided by Express RE
Marketing. We are *not responsible* for any undelivered mail or printing
and cutting issues.
Prior to receiving a final draft and/or having your final draft sent to
print and mail you must pay the invoice in full.

**Comment by hermbit** [comment]
Yep, it will now! I added some code today that displays it in a nicer format and shows how long ago it was, this format will also convert the timezone too.

**Comment by Joshrlear** [comment]
👍

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

*- Josh Lear*
*  Owner, Express RE Marketing*
*  619-507-6807*
  *Website <https://sites.google.com/view/expressremarketing/home> -
Facebook <https://www.facebook.com/expressREmarketing/>*

<https://sites.google.com/view/expressremarketing/automation>
<https://sites.google.com/view/expressremarketing/designs>
<https://sites.google.com/view/expressremarketing/home>
<https://sites.google.com/view/expressremarketing/home>

*Pricing and Project Timeline Disclaimer:*
Express RE Marketing project timeline has a *14 day deadline, *timeline
starts only after receiving the required information.* Any additional time
required will accrue a fee of $5.00/day. *
All "Template Projects" have a *Flat Fee of $15.00*. *Any changes required
on a Template Project will result in an upgrade to Custom Project pricing. *
All "Custom Projects" are subject to custom pricing. Custom Projects
include two free drafts, with a maximum of three changes per draft, drafts
unlimited.
Please submit all changes at the beginning of the day to allow a turnaround
time of 24 hours.
Print and mail set up is a *complimentary* service provided by Express RE
Marketing. We are *not responsible* for any undelivered mail or printing
and cutting issues.
Prior to receiving a final draft and/or having your final draft sent to
print and mail you must pay the invoice in full.
