### ISSUE TITLE
require list title and make fields more obvious

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#139]
currently if no title is given and you select to create the list it continually loads and doesn't create the list. Lets make it required to create a title before the list saves.

Also, it's difficult to see the fields where its asking which columns to upload.

![image](https://user-images.githubusercontent.com/35083202/36322949-4905944e-131d-11e8-92cf-9908cfad4323.png)

**Comment by hermbit** [comment]
I made the list title required, and spread each row out a little more. I see they were squished together, if that's what you meant about being hard to see.

If you have a different idea for the layout I'd be happy to do it, just let me know.

**Comment by Joshrlear** [comment]
​Giving it space definitely helps but if we could bold the field titles a
little and make the "select a​ field" wording a little lighter, slightly
ghosted.

[image: Inline image 1]

*- Josh Lear*
*  Owner, Express RE Marketing*
*  619-507-6807*
  *Website <https://sites.google.com/view/expressremarketing/home> -
Facebook <https://www.facebook.com/expressREmarketing/>*

<https://sites.google.com/view/expressremarketing/automation>
<https://sites.google.com/view/expressremarketing/designs>
<https://sites.google.com/view/expressremarketing/home>
<https://sites.google.com/view/expressremarketing/home>

*Pricing and Project Timeline Disclaimer:*
Express RE Marketing project timeline has a *14 day deadline, *timeline
starts only after receiving the required information.* Any additional time
required will accrue a fee of $5.00/day. *
All "Template Projects" have a *Flat Fee of $15.00*. *Any changes required
on a Template Project will result in an upgrade to Custom Project pricing. *
All "Custom Projects" are subject to custom pricing. Custom Projects
include two free drafts, with a maximum of three changes per draft, drafts
unlimited.
Please submit all changes at the beginning of the day to allow a turnaround
time of 24 hours.
Print and mail set up is a *complimentary* service provided by Express RE
Marketing. We are *not responsible* for any undelivered mail or printing
and cutting issues.
Prior to receiving a final draft and/or having your final draft sent to
print and mail you must pay the invoice in full.

**Comment by Joshrlear** [comment]
Also, please make sure that the save button can't be clicked until the
title is filled in and it shows red text that states the need to make a
title. Currently it allows them to click and it just loads indefinitely.

*- Josh Lear*
*  Owner, Express RE Marketing*
*  619-507-6807*
  *Website <https://sites.google.com/view/expressremarketing/home> -
Facebook <https://www.facebook.com/expressREmarketing/>*

<https://sites.google.com/view/expressremarketing/automation>
<https://sites.google.com/view/expressremarketing/designs>
<https://sites.google.com/view/expressremarketing/home>
<https://sites.google.com/view/expressremarketing/home>

*Pricing and Project Timeline Disclaimer:*
Express RE Marketing project timeline has a *14 day deadline, *timeline
starts only after receiving the required information.* Any additional time
required will accrue a fee of $5.00/day. *
All "Template Projects" have a *Flat Fee of $15.00*. *Any changes required
on a Template Project will result in an upgrade to Custom Project pricing. *
All "Custom Projects" are subject to custom pricing. Custom Projects
include two free drafts, with a maximum of three changes per draft, drafts
unlimited.
Please submit all changes at the beginning of the day to allow a turnaround
time of 24 hours.
Print and mail set up is a *complimentary* service provided by Express RE
Marketing. We are *not responsible* for any undelivered mail or printing
and cutting issues.
Prior to receiving a final draft and/or having your final draft sent to
print and mail you must pay the invoice in full.
