### ISSUE TITLE
Copying the preview image in the payment section

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#150]
It allows for me to right click the picture > open image in new tab. After doing that you are able to copy full resolution image without payment.

![image](https://user-images.githubusercontent.com/35083202/37487447-f66768b0-2867-11e8-98ed-a5b51d795562.png)

![image](https://user-images.githubusercontent.com/35083202/37487494-123abc86-2868-11e8-936b-13afb81d9de4.png)

and then you can expand this page for a full res image

![image](https://user-images.githubusercontent.com/35083202/37487608-61b981b6-2868-11e8-8abf-8596e7d6b044.png)

![image](https://user-images.githubusercontent.com/35083202/37487660-a0206bea-2868-11e8-9940-d6ccfdb136fe.png)

**Comment by hermbit** [comment]
fixed; the image can no longer be right clicked or dragged off the page in any way.
