### ISSUE TITLE
Order/mailing list tracking per agent

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#153]
Currently we can see what orders/mailing lists have been made but no way of seeing what agent they were made for. We need a field and a way to sort and filter by agent or some other way of tracking individual agents orders and for seeing what agent a particular list belongs to.

In addition, for mailing lists these need to be specific to each agent so that the marketing pieces aren't sent to the wrong list.

**Comment by hermbit** [comment]
Fixed - i've now integrated the mailing lists with the agent manager! There's now a tab in the "view agent" page to view the mailing lists for that agent.
