### ISSUE TITLE
Manager/Agent_View and create mailing lists

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#156]
Need a way to display agents lists on the managers mailing list area.

As a manager, if I create a list for an agent, I would like to be able to create it on my mailing list area (when uploading csv mailing list and selecting fields and title it should allow me to choose what agent this list is being created for) rather than needing to go to their profile > click: agents mailing lists > and create new list. 

In addition, when an agent that I manage creates a mailing list on their profile I would like that list to automatically show in my mailing list area and vice versa, if I create a list for them I would like that list to show in that agents mailing list area. 

Something to keep in mind, when a manager is no longer managing an agent they should no longer be able to view that agents lists, even if that manager created that agents lists. Mailing lists should stay with the agent, not the manager.

![manager-agent_mailinglistareas](https://user-images.githubusercontent.com/35083202/37557972-e642615c-29e2-11e8-9fd7-f540ebe4d174.png)

**Comment by hermbit** [comment]
Got this working!

**Comment by Joshrlear** [comment]
Awesome! I'll check this out soon 👍

*- Josh Lear*
*  Owner, Express RE Marketing*
*  619-507-6807*
  *Website <https://sites.google.com/view/expressremarketing/home> -
Facebook <https://www.facebook.com/expressREmarketing/>*

<https://sites.google.com/view/expressremarketing/automation>
<https://sites.google.com/view/expressremarketing/designs>
<https://sites.google.com/view/expressremarketing/home>
<https://sites.google.com/view/expressremarketing/home>

*Pricing and Project Timeline Disclaimer:*
Express RE Marketing project timeline has a *14 day deadline, *timeline
starts only after receiving the required information.* Any additional time
required will accrue a fee of $5.00/day. *
All "Template Projects" have a *Flat Fee of $20.00*. *Any changes required
on a Template Project will result in an upgrade to Custom Project pricing. *
All "Custom Projects" are subject to custom pricing. Custom Projects
include two free drafts, with a maximum of three changes per draft, drafts
unlimited.
Please submit all changes at the beginning of the day to allow a turnaround
time of 24 hours.
Print and mail set up is a *complimentary* service provided by Express RE
Marketing. We are *not responsible* for any undelivered mail or printing
and cutting issues.
Prior to receiving a final draft and/or having your final draft sent to
print and mail you must pay the invoice in full.
