### ISSUE TITLE
spaces in contact message box 

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#16]
It looks like there are a bunch of spaces in the box making it so that you can't see where it says "Message" unless you delete all of them. See pic attached.

![capture](https://user-images.githubusercontent.com/35083202/35159672-f7d42a74-fd08-11e7-82a9-e90c490e7609.PNG)

**Comment by royceshayegan** [comment]
fixed. waiting for merge.

**Comment by Joshrlear** [comment]
thank you

**Comment by hermbit** [comment]
fixed in #17
