### ISSUE TITLE
make user designer fill entire screen

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#28]
I feel like this floating box isn’t giving us very much room for design and places for the text to show on the side, would it be easier to try to use a design similar to Canva? (picture attached) If it will work then there is no need to change to the Canva style, I just thought it'd be good to see another option if it would make things better. If we can make the current style work then lets keep it because I think it's more user friendly. Let me know what you think. Thank you
![canva designer](https://user-images.githubusercontent.com/35083202/35342046-1480b558-00f5-11e8-861c-1563ca32d795.PNG)

**Comment by hermbit** [comment]
I think the current layout we have is more user-friendly yes, but I'll make it fill the entire window instead of being in a "floating box" in the middle. This will give us more room to work with. I'll convert this into an enhancement issue.
