### ISSUE TITLE
Image editor

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#32]
Can we add a picture editor so that people can make their pictures look better?

**Comment by hermbit** [comment]
Can you explain a little more? What features do you have in mind for this?

**Comment by Joshrlear** [comment]
Things like brightness, contrast, color saturation, warm/cold filter,
basically this plus filters to make pictures look nicer.

Also, I use a website called lunapic.com,(this feature is also in
publisher) it lets you remove the background if it can identify the
background and replace it with another picture. For example, a picture if
the front of a house has cloudy sky's so they decided to change the
background to blue skys or a sunset by changing the background image and
blending the two colors together. This may be way too advanced but I do
this sometimes for my clients and it would be a neat feature.

On Jan 24, 2018 8:59 PM, "Michael Auderer" <notifications@github.com> wrote:

Can you explain a little more? What features do you have in mind for this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Joshrlear/Sprynamics/issues/32#issuecomment-360336566>,
or mute the thread
