### ISSUE TITLE
Patterns and colors

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#33]
Maybe add the ability to add patterns that blend with the user’s colors (colors chosen for their design). On the attached design you can see a pattern I used for the background. It'd be nice to have patterns they could choose from and maybe even the ability to use their logo (mostly transparent so that the pattern isn't so strong) as a background pattern. What do you think?
![style 3 - flyer_no bleed-1](https://user-images.githubusercontent.com/35083202/35346657-d7302326-0100-11e8-83fd-68630240742e.png)

**Comment by hermbit** [comment]
This is a cool idea... might take a little while to get it just right, but it's possible. We could have it where you or the user uploads an image to be the background pattern. I guess that would fit in on the "colors" tab.

**Comment by Joshrlear** [comment]
If you could do it that would be great. Especially if you could upload
something like a logo and use it as a tiled background with the ability to
tilt and change transparency. This isn't necessity though so if it takes
too much time then i can try to implement later down the line.
