### ISSUE TITLE
Zillow comps API

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#37]
Can we add this API from Zillow: <https://www.zillow.com/howto/api/GetDeepComps.htm> which gives the ability to pull comparable property sales? I’d like to allow users to not only show where the property is on the map but also be able to show nearby sold properties (also if they could choose which comparables showed that would be a plus but not necessary now). This would add an additional charge to the total cost of the design so we would need to add the extra cost and make it known to the user that it will cost extra (don’t know how much yet… probably $5).

**Comment by hermbit** [comment]
Yeah, this is possible.. it could probably be used in conjunction with the Google API to show this.

**Comment by Joshrlear** [comment]
It would be great if we could. I would probably need to add some new
designs for it to be implemented.
