### ISSUE TITLE
Object features

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#45]
Ability to bend, fold (similar to folding and turn pages in a book), rotate, tilt/slant objects.

**Comment by hermbit** [comment]
rotating/tilting/slanting is added. hold shift while dragging the points to slant the object. folding is much more advanced rendering, it would be better to use an existing rendering program to create a page curl and overlay it as an image, rather than trying to reinvent it.

**Comment by Joshrlear** [comment]
How do we use existing rendering programs? Is it something I need to buy?

On Jan 29, 2018 3:26 AM, "Michael Auderer" <notifications@github.com> wrote:

rotating/tilting/slanting is added. hold shift while dragging the points to
slant the object. folding is much more advanced rendering, it would be
better to use an existing rendering program to create a page curl and
overlay it as an image, rather than trying to reinvent it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Joshrlear/Sprynamics/issues/45#issuecomment-361172192>,
or mute the thread

**Comment by hermbit** [comment]
For example, Photoshop has an advanced warping engine which can create this effect: https://www.youtube.com/watch?v=kD0O6FZnpRc

**Comment by Joshrlear** [comment]
So I'm guessing your saying that there is nothing that we can buy to make
this happen on the website, correct?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

*- Josh Lear*
*  Owner, Express RE Marketing*
*  619-507-6807*
  *Website <https://sites.google.com/view/expressremarketing/home> -
Facebook <https://www.facebook.com/expressREmarketing/>*

<https://sites.google.com/view/expressremarketing/automation>
<https://sites.google.com/view/expressremarketing/designs>
<https://sites.google.com/view/expressremarketing/home>
<https://sites.google.com/view/expressremarketing/home>

*Pricing and Project Timeline Disclaimer:*
Express RE Marketing project timeline has a *14 day deadline, *timeline
starts only after receiving the required information.* Any additional time
required will accrue a fee of $5.00/day. *
All "Template Projects" have a *Flat Fee of $15.00*. *Any changes required
on a Template Project will result in an upgrade to Custom Project pricing. *
All "Custom Projects" are subject to custom pricing. Custom Projects
include two free drafts, with a maximum of three changes per draft, drafts
unlimited.
Please submit all changes at the beginning of the day to allow a turnaround
time of 24 hours.
Print and mail set up is a *complimentary* service provided by Express RE
Marketing. We are *not responsible* for any undelivered mail or printing
and cutting issues.
Prior to receiving a final draft and/or having your final draft sent to
print and mail you must pay the invoice in full.
