### ISSUE TITLE
Shadow size

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#47]
Allow to make shadow bigger and smaller.

**Comment by hermbit** [comment]
Unfortunately web canvas doesn't support shadow size, only shadow color / blur / offsets. I believe all of your designs should still be achievable by playing with a combination of blur, opacity, and offsets. 

I even tried creating a "ghost" rectangle for each rectangle, that would allow a smaller shadow.. but unfortunately the color of the shadow is linked to the rectangle itself. It has something to do with the way canvas renders graphics. Even if the "ghost" rectangle worked, it would be a big task to link it to everything else in the designer, but unfortunately there doesn't seem to be a workaround right now.

**Comment by Joshrlear** [comment]
That's unfortunate but thank you for looking into it
