### ISSUE TITLE
Image features

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#57]
Need pictures to have all the same abilities of shapes (shadow, borders, etc.) Also, I need a crop tool (regular crop and crop to a specific shape like a Scalene Triangle or circle).

**Comment by hermbit** [comment]
Is this a duplicate of #40 ?

**Comment by Joshrlear** [comment]
No, I was probably referring to shapes in the other one. I need pictures on
the admin side to be able to have shadows, and crop into different shapes.
On the user side I want them to be able to crop there pictures to perfectly
fit in the area given on the design.

**Comment by hermbit** [comment]
Oops, I asked that in the wrong issue. Disregard that question.
