### ISSUE TITLE
Profile info verification

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#73]
Columns like email and the users address need to be verified by confirmation emails and google api. Also, currently I can remove the .com and anything else from the email column without it flagging as an issue. the email column should only allow emails, the phone should only allow phones, and so on.

**Comment by hermbit** [comment]
What google API are you referring to?

**Comment by Joshrlear** [comment]
I believe Google places api can verify addresses

On Jan 27, 2018 4:56 AM, "Michael Auderer" <notifications@github.com> wrote:

What google API are you referring to?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Joshrlear/Sprynamics/issues/73#issuecomment-360973994>,
or mute the thread
