### ISSUE TITLE
Profile look and uploading pictures/logo to profile

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#78]
Please refer to these pictures for a general idea of how I’d like the profile to look. There is one from Canva and another from Corefact.

It'd be good to have a nav bar on the side for profile and account info as well as changing passwords, past orders, saved templates, and mailing lists. I also like how it clearly shows what each field is and they show in a editing box so that the user knows that they can easily edit different info.

Also, it would be great if we could allow the ability for users to use images from their social media and from other url links.

![profile style-canva](https://user-images.githubusercontent.com/35083202/35409624-c802c648-01e0-11e8-9a91-974f0ec8b644.PNG)
![profile style-canva2](https://user-images.githubusercontent.com/35083202/35409626-c81342fc-01e0-11e8-83b8-f246329ffca5.PNG)
![profile style-canva3](https://user-images.githubusercontent.com/35083202/35409627-c82df994-01e0-11e8-95b2-67ed31f484b6.PNG)
![profile style-corefact](https://user-images.githubusercontent.com/35083202/35409628-c83f8704-01e0-11e8-9eb8-674709dd2fec.PNG)

**Comment by hermbit** [comment]
Just finished a big revamp that includes this sidebar!
