### ISSUE TITLE
social media icons on home page

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#83]
Social media buttons in the contact section need to be linked to the correct urls (I would also like the buttons to either light up like on the designer size selection area or get bigger as you scroll over them showing that you are selecting one or the other).

So far I only have Facebook: 
Facebook.com/sprynamics

I have a google+ but can't figure out how to get my url

I will send the rest when I can.

**Comment by hermbit** [comment]
Got them increasing in size on hover now, and the facebook button is now linked up. Just let me know when you get the others done.
