### ISSUE TITLE
Sign up/Login look

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#88]
Needs to look the same as the "https://sprynamics.com/products" page or the "https://sprynamics.com/products" page.  I want this website to have a similar look throughout.

Also, make login and sign up a lot more like the login and sign up section of Canva.com with a smaller vertical white section rather than the more horizontal one we currently have.

![canva login](https://user-images.githubusercontent.com/35083202/35461511-37d61da0-02b6-11e8-8413-a73d917f1b93.PNG)
![canva sign up](https://user-images.githubusercontent.com/35083202/35461512-37e2ab6a-02b6-11e8-812c-ce9856410f72.PNG)

**Comment by hermbit** [comment]
![image](https://user-images.githubusercontent.com/28285686/35722673-3d285976-07c5-11e8-8fc7-c7cc9949dc06.png)
